# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_service_pb2 as calculator__service__pb2


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGreeting = channel.unary_unary(
                '/RouteGuide/GetGreeting',
                request_serializer=calculator__service__pb2.emptyMessageReuqest.SerializeToString,
                response_deserializer=calculator__service__pb2.greetingResponse.FromString,
                )
        self.GetAnswer = channel.unary_unary(
                '/RouteGuide/GetAnswer',
                request_serializer=calculator__service__pb2.argumentsRequest.SerializeToString,
                response_deserializer=calculator__service__pb2.answerResponse.FromString,
                )


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGreeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGreeting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGreeting,
                    request_deserializer=calculator__service__pb2.emptyMessageReuqest.FromString,
                    response_serializer=calculator__service__pb2.greetingResponse.SerializeToString,
            ),
            'GetAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswer,
                    request_deserializer=calculator__service__pb2.argumentsRequest.FromString,
                    response_serializer=calculator__service__pb2.answerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGreeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RouteGuide/GetGreeting',
            calculator__service__pb2.emptyMessageReuqest.SerializeToString,
            calculator__service__pb2.greetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RouteGuide/GetAnswer',
            calculator__service__pb2.argumentsRequest.SerializeToString,
            calculator__service__pb2.answerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
