# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63\x61lculator_service.proto\",\n\x10greetingResponse\x12\x18\n\x10greeting_message\x18\x01 \x01(\t\"\x15\n\x13\x65mptyMessageReuqest\"=\n\x10\x61rgumentsRequest\x12\x0b\n\x03op1\x18\x01 \x01(\x02\x12\x0b\n\x03op2\x18\x02 \x01(\x02\x12\x0f\n\x07operand\x18\x03 \x01(\t\"+\n\x0e\x61nswerResponse\x12\x19\n\x11\x63\x61lculator_answer\x18\x01 \x01(\x02\x32y\n\nRouteGuide\x12\x38\n\x0bGetGreeting\x12\x14.emptyMessageReuqest\x1a\x11.greetingResponse\"\x00\x12\x31\n\tGetAnswer\x12\x11.argumentsRequest\x1a\x0f.answerResponse\"\x00\x62\x06proto3'
)




_GREETINGRESPONSE = _descriptor.Descriptor(
  name='greetingResponse',
  full_name='greetingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting_message', full_name='greetingResponse.greeting_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=72,
)


_EMPTYMESSAGEREUQEST = _descriptor.Descriptor(
  name='emptyMessageReuqest',
  full_name='emptyMessageReuqest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=95,
)


_ARGUMENTSREQUEST = _descriptor.Descriptor(
  name='argumentsRequest',
  full_name='argumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op1', full_name='argumentsRequest.op1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op2', full_name='argumentsRequest.op2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operand', full_name='argumentsRequest.operand', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=158,
)


_ANSWERRESPONSE = _descriptor.Descriptor(
  name='answerResponse',
  full_name='answerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calculator_answer', full_name='answerResponse.calculator_answer', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['greetingResponse'] = _GREETINGRESPONSE
DESCRIPTOR.message_types_by_name['emptyMessageReuqest'] = _EMPTYMESSAGEREUQEST
DESCRIPTOR.message_types_by_name['argumentsRequest'] = _ARGUMENTSREQUEST
DESCRIPTOR.message_types_by_name['answerResponse'] = _ANSWERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

greetingResponse = _reflection.GeneratedProtocolMessageType('greetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:greetingResponse)
  })
_sym_db.RegisterMessage(greetingResponse)

emptyMessageReuqest = _reflection.GeneratedProtocolMessageType('emptyMessageReuqest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGEREUQEST,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:emptyMessageReuqest)
  })
_sym_db.RegisterMessage(emptyMessageReuqest)

argumentsRequest = _reflection.GeneratedProtocolMessageType('argumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARGUMENTSREQUEST,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:argumentsRequest)
  })
_sym_db.RegisterMessage(argumentsRequest)

answerResponse = _reflection.GeneratedProtocolMessageType('answerResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERRESPONSE,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:answerResponse)
  })
_sym_db.RegisterMessage(answerResponse)



_ROUTEGUIDE = _descriptor.ServiceDescriptor(
  name='RouteGuide',
  full_name='RouteGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=205,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetGreeting',
    full_name='RouteGuide.GetGreeting',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGEREUQEST,
    output_type=_GREETINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAnswer',
    full_name='RouteGuide.GetAnswer',
    index=1,
    containing_service=None,
    input_type=_ARGUMENTSREQUEST,
    output_type=_ANSWERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEGUIDE)

DESCRIPTOR.services_by_name['RouteGuide'] = _ROUTEGUIDE

# @@protoc_insertion_point(module_scope)
